/* The following code was generated by JFlex 1.6.1 */

/**
 * This is an example JFlex specification for the language given by the
 * regular expression:
 *
 *     [a-z_]+ | [0-9]+ | if | while | ;
 */

package antgame;

import java.io.InputStreamReader;
import tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/Users/oliverthomas/Google Drive/Degree/antBrainLexer.jflex</tt>
 */
public class GeneratedAntBrainLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\43\1\42\1\0\1\43\1\41\22\0\1\43\17\44\12\26"+
    "\1\44\1\46\5\44\1\30\2\45\1\17\1\45\1\24\1\45\1\27"+
    "\3\45\1\33\1\5\2\45\1\13\1\45\1\36\1\1\1\21\1\11"+
    "\1\45\1\40\3\45\6\44\1\6\1\45\1\15\1\32\1\2\1\34"+
    "\1\37\1\31\1\14\1\45\1\10\1\25\1\12\1\3\1\20\1\16"+
    "\1\45\1\7\1\4\1\35\1\22\1\23\4\45\4\44\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff91\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\11\1\1\2\4\1\2\3\1\4\1\5\21\0"+
    "\1\5\10\0\1\6\7\0\2\7\6\0\1\6\1\10"+
    "\1\0\1\11\6\0\1\6\6\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\234\0\303\0\352\0\u0111"+
    "\0\u0138\0\u015f\0\u0186\0\u01ad\0\u01d4\0\u01fb\0\u0222\0\u0249"+
    "\0\47\0\47\0\u0270\0\165\0\u0297\0\u02be\0\u02e5\0\u030c"+
    "\0\u0333\0\u035a\0\u0381\0\u03a8\0\u03cf\0\u03f6\0\u041d\0\u0444"+
    "\0\u046b\0\u0492\0\u04b9\0\u04e0\0\u0507\0\u052e\0\u0555\0\u057c"+
    "\0\u05a3\0\u05ca\0\u05f1\0\u0618\0\u063f\0\u0666\0\u068d\0\u06b4"+
    "\0\u06db\0\u0702\0\u0729\0\u0750\0\u0777\0\u079e\0\165\0\u07c5"+
    "\0\u07ec\0\u0813\0\u083a\0\u0861\0\u0888\0\165\0\165\0\u08af"+
    "\0\u08d6\0\u08fd\0\u0924\0\u094b\0\u0972\0\u0999\0\u01d4\0\u09c0"+
    "\0\u09e7\0\u0a0e\0\u079e\0\u0a35\0\u0a5c\0\u0a83";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\3\4\1\5\3\4\1\6\1\4\1\7"+
    "\3\4\1\10\1\4\1\11\2\4\1\12\1\4\1\13"+
    "\1\14\1\15\2\4\1\16\2\4\1\17\2\4\1\20"+
    "\1\21\1\22\1\2\1\4\1\23\50\0\1\24\1\25"+
    "\36\24\1\20\1\21\2\0\1\24\2\0\40\24\1\20"+
    "\1\21\2\0\1\24\2\0\5\24\1\26\11\24\1\27"+
    "\20\24\1\20\1\21\2\0\1\24\2\0\2\24\1\30"+
    "\35\24\1\20\1\21\2\0\1\24\2\0\13\24\1\31"+
    "\24\24\1\20\1\21\2\0\1\24\2\0\6\24\1\32"+
    "\31\24\1\20\1\21\2\0\1\24\2\0\21\24\1\33"+
    "\16\24\1\20\1\21\2\0\1\24\2\0\6\24\1\34"+
    "\10\24\1\35\4\24\1\36\13\24\1\20\1\21\2\0"+
    "\1\24\2\0\25\24\1\13\12\24\1\20\1\21\2\0"+
    "\1\24\2\0\1\24\1\37\15\24\1\40\20\24\1\20"+
    "\1\21\2\0\1\24\2\0\30\24\1\41\7\24\1\20"+
    "\1\21\2\0\1\24\2\0\1\24\1\42\36\24\1\20"+
    "\1\21\2\0\1\24\2\0\13\24\1\43\3\24\1\44"+
    "\20\24\1\20\1\21\2\0\1\24\43\0\1\21\5\0"+
    "\40\23\2\45\4\23\1\0\2\24\1\46\35\24\1\20"+
    "\1\21\2\0\1\24\2\0\6\24\1\47\31\24\1\20"+
    "\1\21\2\0\1\24\2\0\22\24\1\50\15\24\1\20"+
    "\1\21\2\0\1\24\2\0\11\24\1\51\26\24\1\20"+
    "\1\21\2\0\1\24\2\0\14\24\1\52\23\24\1\20"+
    "\1\21\2\0\1\24\2\0\17\24\1\53\20\24\1\20"+
    "\1\21\2\0\1\24\2\0\6\24\1\54\31\24\1\20"+
    "\1\21\2\0\1\24\2\0\13\24\1\55\24\24\1\20"+
    "\1\21\2\0\1\24\2\0\1\24\1\56\15\24\1\57"+
    "\20\24\1\20\1\21\2\0\1\24\2\0\13\24\1\53"+
    "\24\24\1\20\1\21\2\0\1\24\2\0\6\24\1\60"+
    "\31\24\1\20\1\21\2\0\1\24\2\0\11\24\1\61"+
    "\26\24\1\20\1\21\2\0\1\24\2\0\1\24\1\62"+
    "\36\24\1\20\1\21\2\0\1\24\2\0\33\24\1\63"+
    "\4\24\1\20\1\21\2\0\1\24\2\0\36\24\1\64"+
    "\1\24\1\20\1\21\2\0\1\24\2\0\14\24\1\65"+
    "\23\24\1\20\1\21\2\0\1\24\42\0\2\45\5\0"+
    "\3\24\1\50\34\24\1\20\1\21\2\0\1\24\2\0"+
    "\7\24\1\66\30\24\1\20\1\21\2\0\1\24\2\0"+
    "\1\24\1\67\36\24\1\20\1\21\2\0\1\24\2\0"+
    "\5\24\1\70\32\24\1\20\1\21\2\0\1\24\2\0"+
    "\7\24\1\71\30\24\1\20\1\21\2\0\1\24\2\0"+
    "\15\24\1\67\22\24\1\20\1\21\2\0\1\24\2\0"+
    "\2\24\1\67\35\24\1\20\1\21\2\0\1\24\2\0"+
    "\1\24\1\72\36\24\1\20\1\21\2\0\1\24\2\0"+
    "\4\24\1\73\21\24\1\74\10\24\1\75\1\20\1\21"+
    "\2\0\1\24\2\0\31\24\1\76\6\24\1\20\1\21"+
    "\2\0\1\24\2\0\1\24\1\77\36\24\1\20\1\21"+
    "\2\0\1\24\2\0\1\24\1\76\36\24\1\20\1\21"+
    "\2\0\1\24\2\0\5\24\1\100\32\24\1\20\1\21"+
    "\2\0\1\24\2\0\34\24\1\101\3\24\1\20\1\21"+
    "\2\0\1\24\2\0\30\24\1\63\7\24\1\20\1\21"+
    "\2\0\1\24\2\0\7\24\1\76\30\24\1\20\1\21"+
    "\2\0\1\24\2\0\1\24\1\102\36\24\1\20\1\21"+
    "\2\0\1\24\2\0\6\24\1\103\31\24\1\20\1\21"+
    "\2\0\1\24\2\0\10\24\1\53\27\24\1\20\1\21"+
    "\2\0\1\24\2\0\2\24\1\104\35\24\1\20\1\21"+
    "\2\0\1\24\2\0\5\24\1\105\32\24\1\20\1\21"+
    "\2\0\1\24\2\0\17\24\1\40\20\24\1\20\1\21"+
    "\2\0\1\24\2\0\13\24\1\106\24\24\1\20\1\21"+
    "\2\0\1\24\2\0\31\24\1\77\6\24\1\20\1\21"+
    "\2\0\1\24\2\0\27\24\1\107\10\24\1\20\1\21"+
    "\2\0\1\24\2\0\6\24\1\76\31\24\1\20\1\21"+
    "\2\0\1\24\2\0\7\24\1\67\30\24\1\20\1\21"+
    "\2\0\1\24\2\0\31\24\1\110\6\24\1\20\1\21"+
    "\2\0\1\24\2\0\6\24\1\111\31\24\1\20\1\21"+
    "\2\0\1\24\2\0\34\24\1\112\3\24\1\20\1\21"+
    "\2\0\1\24\2\0\37\24\1\75\1\20\1\21\2\0"+
    "\1\24\2\0\7\24\1\113\30\24\1\20\1\21\2\0"+
    "\1\24\2\0\30\24\1\114\7\24\1\20\1\21\2\0"+
    "\1\24\2\0\23\24\1\115\14\24\1\20\1\21\2\0"+
    "\1\24\2\0\17\24\1\116\20\24\1\20\1\21\2\0"+
    "\1\24\2\0\17\24\1\57\20\24\1\20\1\21\2\0"+
    "\1\24\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2730];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\16\1\2\11\1\1\21\0\1\1\10\0"+
    "\1\1\7\0\2\1\6\0\2\1\1\0\1\1\6\0"+
    "\1\1\6\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    // java code can go here


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public GeneratedAntBrainLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 150) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal text <"+yytext()+">");
            }
          case 10: break;
          case 2: 
            { return new TokenInt(Integer.parseInt(yytext()));
            }
          case 11: break;
          case 3: 
            { return new TokenName(yytext());
            }
          case 12: break;
          case 4: 
            { /* ignore whitespace */
            }
          case 13: break;
          case 5: 
            { /* ignore comment */
            }
          case 14: break;
          case 6: 
            { return new TokenCondition(yytext());
            }
          case 15: break;
          case 7: 
            { return new TokenInstruction(yytext());
            }
          case 16: break;
          case 8: 
            { return new TokenDirection(yytext());
            }
          case 17: break;
          case 9: 
            { return new TokenTurn(yytext());
            }
          case 18: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
